name:                dirsize
version:             0.1.0.0
github:              "Angramme/dirsize"
license:             BSD3
author:              "Kacper Ozieblowski"
maintainer:          "example@example.com"
copyright:           "2020 Kacper Ozieblowski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Angramme/dirsize#readme>

dependencies:
- base >= 4.7 && < 5
- filepath
- directory
- parallel-io
- colour
- ansi-terminal

library:
  source-dirs: src

executables:
  dirsize:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - dirsize

tests:
  dirsize-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dirsize
